### PR TITLE
63 page faq

### LINKED ISSUE #63: Page: FAQ

### PR DESCRIPTION
**Pull request by luciemariec**
- Created FAQ with 5 Accordion Bootstrap buttons
- Created FAQHeader to display main site navigation
- Created FAQ.css for styling
- Linked FAQ page to Footer on main

### CODE REVIEW

**Review by byndas — CHANGES_REQUESTED** [review]
- in FAQ.css, move body font-family to a specific section, otherwise will affect entire site
- rename header to faq-header & .container to .faq-container --> these will affect header & .container on other pages
- change line 22 of TripDetailsPage to: 
            axios.get('/api/public/trips/' + ("123456".includes(id) ? id : "1"))

**Comment by luciemariec** [comment]
- Fixed FAQ.css and FAQHeader
- Changed line 22 on Trip Details page

**Review by byndas — DISMISSED** [review]
thanks for fixing styles

**Review by byndas — APPROVED** [review]
resolved merge conflict

**Pull request merged**
